In [2]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # one level up from tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from src.inference_pipeline.inference import predict

# Load a few rows of already preprocessed data
sample_path = ROOT / "data/raw/base_lol.csv"
df = pd.read_csv(sample_path).sample(5, random_state=42).reset_index(drop=True)


print("Input sample:")
display(df.head())

# Run inference
preds_df = predict(df)
print("✅ Predictions returned")
display(preds_df[["predicted_winner"]].head())

Input sample:

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,...,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
0,4516180818,1,20,1,1,5,6,6,1,1,...,0,16643,6.8,17556,210,48,608,703,21.0,1664.3
1,4517684472,0,13,1,0,1,3,1,0,0,...,0,17065,7.2,19934,250,76,2373,1592,25.0,1706.5
2,4468356736,0,14,2,1,10,10,17,1,1,...,0,17860,7.2,18838,206,56,-987,-642,20.6,1786.0
3,4507786946,1,16,2,1,7,6,7,2,1,...,0,15975,7.0,17368,199,62,-1478,-483,19.9,1597.5
4,4515728718,0,11,0,0,5,8,1,0,0,...,0,18339,7.4,20334,229,59,3750,4961,22.9,1833.9

✅ Data processing completed (saved to \opt\airflow\dags\data\cleaned).
Processed Data: (5, 39)
✅ Predictions returned

   predicted_winner
0                 0
1                 0
2                 1
3                 1
4                 0